FROM node:latest AS frontend-builder

WORKDIR /app/frontend

COPY frontend/package.json frontend/package-lock.json ./

RUN npm config set registry https://registry.npmjs.org/

RUN npm install -g npm@10.2.5

RUN npm install --save-dev @babel/plugin-transform-private-methods

RUN npm install --unsafe-perm --network-timeout=60000

COPY frontend .

EXPOSE 3000

CMD ["npm", "run", "start"]
